version: 2.1
commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo "Hello "
      - run: echo << parameters.to >>
  sayyoo:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Yoo World"
    steps:
      - run: echo "Yoo "
      - run: echo << parameters.to >>

jobs:
  build:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - sayhello:
          to: "James"
      - sayyoo:
          to: "James"